production: false
# Site settings
title: PhoneGap
description: "Easily create apps using the web technologies you know and love: HTML, CSS, and JavaScript."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: phonegap
github_username:  phonegap

paginate: 10
paginate_list_count: 7
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown

permalink: /:categories/:title/
highlighter: rouge
excerpt_separator: <!--more-->
exclude:
  - vendor
  - blog
sass:
  sass_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      extra_js:
        - taglist.js
